server:
  port: 9090
spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**